### ISSUE TITLE
NVCC Error

### ISSUE THREAD

**Issue by Jireh-Jam** [V3du4rd0/AMCF#2]
Hi, thanks for your code here on git. I am interested in your code and i have been getting this error below.
runfile('/home/jireh/AMCF-master/ImageRec_v4.py', wdir='/home/jireh/AMCF-master')
picture loaded...
Traceback (most recent call last):

  File "<ipython-input-1-7428a11a8546>", line 1, in <module>
    runfile('/home/jireh/AMCF-master/ImageRec_v4.py', wdir='/home/jireh/AMCF-master')

  File "/home/jireh/anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "/home/jireh/anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/jireh/AMCF-master/ImageRec_v4.py", line 120, in <module>
    BSys=SourceModule(amcf.Bu)

  File "/home/jireh/anaconda3/lib/python3.6/site-packages/pycuda/compiler.py", line 291, in __init__
    arch, code, cache_dir, include_dirs)

  File "/home/jireh/anaconda3/lib/python3.6/site-packages/pycuda/compiler.py", line 254, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir, target)

  File "/home/jireh/anaconda3/lib/python3.6/site-packages/pycuda/compiler.py", line 137, in compile_plain
    stderr=stderr.decode("utf-8", "replace"))

CompileError: nvcc compilation of /tmp/tmp7d0j8604/kernel.cu failed

I am working on ubuntu and i have this issues. I s there a possibility to implement on python with tensorflow?

**Comment by V3du4rd0** [comment]
(Assuming that you have replaced the Python 2.X print syntax to work with Python 3, and pycuda works correctly in your Anaconda installation) One of your errors seems to be related with the functions BSys and BU. Please download the new version and try to run it again. The original code was only tested using an old version compiler (~2014, v.6.5), and this update works with the newest cuda-toolkit and pycuda too. The error appeared because a function norm in mod_amcf (in BU and Au) is being overwritten. Hope this helps you, I'm not familiar with the other errors.
Since all computations represent a numerical pde solver (arithmetic computations), I think that it can be ported to work with tf. I had not considered to implement this algo on tf.
A new version is now in progress, so that's great to know the issues and inquiries.
